# Configuração do banco H2
spring.datasource.url=jdbc:h2:mem:todoapi
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Faz o Spring criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# Ativa o console visual do H2 no navegador
spring.h2.console.enabled=true

# Mostra os comandos SQL no terminal (útil para aprender)
spring.jpa.show-sql=true